cuda: True
ngpu: 1
gpu_id: '0'
data_dir: ./filelists/Train     # Your dataset path
video_flist: './filelists/Video_Name_List.txt'
audio_flist: './filelists/Audio_Name_List.txt'
workers: 1
batchSize: 40
checkpoint_folder: ./checkpoints
init_model: './checkpoints/Test2_state_epoch10.pth'
topk: 5
